npm install -g @hapi/joi@^17.1.0
npm install -g bcryptjs@^2.4.3
npm install -g connect-mongo@^3.2.0
npm install -g cookie-parser@~1.4.4
npm install -g cors@^2.8.5
npm install -g csurf@^1.11.0
npm install -g debug@~2.6.9
npm install -g express@~4.16.1
npm install -g express-session@^1.17.0
npm install -g http-errors@~1.6.3
npm install -g jade@~1.11.0
npm install -g jsonwebtoken@^8.5.1
npm install -g mongoose@^5.8.9
npm install -g mongoose-ttl@0.0.3
npm install -g mongoose-unique-validator@^2.0.3
npm install -g morgan@~1.9.1
npm install -g nodemailer@^6.4.3
npm install -g passport@^0.4.1
npm install -g passport-local@^1.0.0
npm install -g formidable@^1.2.1
npm install -g i18n
npm install -g async
npm install -g etag
npm install -g request
npm install -g redis
npm install -g lodash
npm install -g mime